import prop1 from './cheppalsherpa.jpg';
import prop2 from './guide1.jpg';
import prop3 from './guide2.jpg';
import prop4 from './guide3.jpg';
import image1 from './guide4.jpg';
import image4 from './guide5.jpg';
import image5 from './guide6.jpg';
import image9 from './cheppalsherpa.jpg';

export const GuideList = [
  {
    name: "Cheppal Sherpa",
    image: prop1,
    price: "30000 Fixed",
    province: "Province 3",
    buyrent: "Rent",
    Experience: "4years",
    Contact: "9803919300",
    Age: "32",
    Language: "English,Hindi,korean",
  },
  {
    name: "Lakpa dolmo sherpa",
    days: "1",
    image: prop2,
    price: "11000-15000",
    province: "Province 3",
    buyrent: "Buy",
    Experience: "8years",
    Contact: "9803919300",
    Age: "40",
    Language: "Nepali",
  },
  {
    name: "Raju lama",
    days: "1",
    image: prop3,
    price: "16000-20000",
    province: "Province 1",
    buyrent: "Rent",
    Experience: "2years",
    Contact: "9803919300",
    Age: "38",
    Language: "Nepali",
  },
  {
    name: "Ganesh Tamang",
    days: "2",
    image: prop4,
    price: "21000",
    province: "Province 4",
    buyrent: "Buy",
    Experience: "4years",
    Contact: "9803919300",
    Age: "37",
    Language: "Nepali,Swedish",
  },
  {
    name: "Bipen rai magar",
    days: "3",
    image: image1,
    price: "5000-10000",
    province: "Province 3",
    buyrent: "Buy",
    Experience: "4years",
    Contact: "9803919300",
    Age: "52",
    Language: "Nepali,French",
  },
  {
    name: "Lipesh limbu",
    days: "4",
    image: image4,
    price: "11000-15000",
    province: "Province 5",
    buyrent: "Rent",
    Experience: "4years",
    Contact: "9803919300",
    Age: "59",
    Language: "Nepali,Urdu",
  },
  {
    name: "Jit magar",
    days: "5",
    image: image5,
    price: "5000-10000",
    province: "Province 1",
    buyrent: "Buy",
    Experience: "4years",
    Contact: "9803919300",
    Age: "60",
    Language: "Nepali,English",
  },
  {
    name: "Muskan lama",
    days: "6",
    image: image9,
    price: "20000",
    province: "Province 5",
    buyrent: "Buy",
    Experience: "4years",
    Contact: "9803919300",
    Age: "39",
    Language: "Nepali,Bengali",
  },
  {
    name: "Rambo thapa",
    days: "7",
    image: prop2,
    price: "20000",
    province: "Province 3",
    buyrent: "Rent",
    Experience: "4years",
    Contact: "9803919300",
    Age: "31",
    Language: "Nepali,Chinese,Korean",
  },
];

